### ISSUE TITLE
Homepage banner & Header icons

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Hai-Cheng-Speed-Work#1]
Sometimes the homepage banner & header icons are not coming in preview.
Preview: https://6z047vhtcy96ghah-56323571898.shopifypreview.com/
SS: 
![image](https://user-images.githubusercontent.com/97726944/164442938-7fb168a8-e98e-41f8-a047-e8824a126bd0.png)

Live: https://www.suprus.com/
SS: 
![image](https://user-images.githubusercontent.com/97726944/164405615-1f533af9-37eb-4acc-89cd-7628992776e3.png)

**Comment by devabulabbas** [comment]
Resolved 
This Is beacuse Of Speed Optimization Work

**Comment by Shoaibans** [comment]
The banner is not comig
Video: https://www.awesomescreenshot.com/video/8537742?key=91de77ac782a180720f4bd17196f960d
