### ISSUE TITLE
Search page images missing

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Hai-Cheng-Speed-Work#10]
The images are missing from search page.
Preview: https://6z047vhtcy96ghah-56323571898.shopifypreview.com/search?q=lighter
SS: 
![image](https://user-images.githubusercontent.com/97726944/164449337-80ef6a93-c535-483a-b7d4-704de79ed2de.png)
Live: https://www.suprus.com/search?q=lighter
SS: 
![image](https://user-images.githubusercontent.com/97726944/164449519-9611df0c-fab6-4c2b-80aa-e685367c4fdf.png)

**Comment by devabulabbas** [comment]
@Shoaibans All images are loading Properly Checked On Incognito also
