### ISSUE TITLE
Footer logo 

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Hai-Cheng-Speed-Work#2]
The logo in the footer is coming small in preview.
Preview: 
![image](https://user-images.githubusercontent.com/97726944/164442075-8fe252a1-89a5-4ef1-97fd-55dc1ca33505.png)
Live: 
![image](https://user-images.githubusercontent.com/97726944/164442145-ca23f41e-5777-4e6c-94c5-3a991bb8a000.png)

**Comment by devabulabbas** [comment]
@Shoaibans 
Resolved
![image](https://user-images.githubusercontent.com/100209490/164688043-e4328ee1-1f78-4c7d-a934-82d2afc711a4.png)
