### ISSUE TITLE
Collection page banner

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Hai-Cheng-Speed-Work#3]
Sometimes the banner in the collection page is not coming in preview. (ALL THE COLLECTION PAGES)
Preview: https://6z047vhtcy96ghah-56323571898.shopifypreview.com/collections/candle
SS: 
![image](https://user-images.githubusercontent.com/97726944/164442506-72376a67-46f7-498f-b158-b7055c6b7910.png)
Live: https://www.suprus.com/collections/candle
SS: 
![image](https://user-images.githubusercontent.com/97726944/164442597-3ed107bf-87e9-40bd-997e-297bef80bd96.png)

**Comment by devabulabbas** [comment]
@Shoaibans 
Resolved
![image](https://user-images.githubusercontent.com/100209490/164685696-ccf0ea86-1662-4d81-94d7-120da4ab54b0.png)
