### ISSUE TITLE
Missing images

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Hai-Cheng-Speed-Work#4]
The Images are not coming in Collection page.
Preview: https://6z047vhtcy96ghah-56323571898.shopifypreview.com/collections
SS: 
![image](https://user-images.githubusercontent.com/97726944/164443568-91f091ee-da83-44ba-ad24-b48e24f14940.png)
Live: https://www.suprus.com/collections
SS: 
![image](https://user-images.githubusercontent.com/97726944/164443777-a6b5ed26-a3ea-4e10-94d3-83cae9778eec.png)

**Comment by devabulabbas** [comment]
@Shoaibans 
![image](https://user-images.githubusercontent.com/100209490/164685450-a9976583-733b-4d6d-8eb4-c5549dfe47e7.png)

**Comment by Shoaibans** [comment]
Not reflecting on my end.

![image](https://user-images.githubusercontent.com/97726944/164705966-f9360c62-a7c8-4dd3-a2ed-c4d5a2ddb3fa.png)
