### ISSUE TITLE
Product images missing.

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Hai-Cheng-Speed-Work#5]
The product image in the collection pages are not reflecting.
Preview: https://6z047vhtcy96ghah-56323571898.shopifypreview.com/collections/candle-lighter-gift-set
SS: 
![image](https://user-images.githubusercontent.com/97726944/164445016-b20c5e83-753f-4af4-9106-07597391ce5b.png)
Live: https://www.suprus.com/collections/candle-lighter-gift-set
SS: 
![image](https://user-images.githubusercontent.com/97726944/164445105-c2eb28c3-be52-4b3b-a1d2-c061e0bda41b.png)

**Comment by devabulabbas** [comment]
@resolved 
![image](https://user-images.githubusercontent.com/100209490/164685118-154ef633-e9b1-4d2c-aebb-9ef452b3e098.png)
