### ISSUE TITLE
Extra content in sortby

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Hai-Cheng-Speed-Work#6]
Extra content is coming in sortby filter box.
**Steps**
1: Go to the collection/search page.
2: Apply sortby filter.
Preview: 
![image](https://user-images.githubusercontent.com/97726944/164445552-5a8bba6f-d93c-4eb5-a7de-176ea25907ef.png)
Live: 
![image](https://user-images.githubusercontent.com/97726944/164445602-1b6834f4-dd2b-49e9-8a0d-b20c986c04ee.png)

**Comment by devabulabbas** [comment]
@Shoaibans 
Resolved

**Comment by Shoaibans** [comment]
Some part is still visible.

![image](https://user-images.githubusercontent.com/97726944/164704933-6302fbac-f047-4142-975c-009c98f717d9.png)

**Comment by devabulabbas** [comment]
Resolved . Will be there because of Anchor text error
