### ISSUE TITLE
Different image size

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Hai-Cheng-Speed-Work#7]
The image in contact page is coming stretched in preview.
Preview: https://6z047vhtcy96ghah-56323571898.shopifypreview.com/pages/contact-us
SS: 
![image](https://user-images.githubusercontent.com/97726944/164446924-93d909a3-4150-41d1-a9d7-eb4dffd0ac6b.png)

Live: https://www.suprus.com/pages/contact-us
SS: 
![image](https://user-images.githubusercontent.com/97726944/164446214-1f505746-5f15-4459-8e61-9905f2235562.png)

**Comment by devabulabbas** [comment]
Resolved
