### ISSUE TITLE
Missing banner &  Stretched image

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Hai-Cheng-Speed-Work#9]
The banner is not coming in About us page & the image is also stretched.
Preview: https://6z047vhtcy96ghah-56323571898.shopifypreview.com/pages/about-us
SS: 
![image](https://user-images.githubusercontent.com/97726944/164447950-4f906593-84e7-4821-9b50-ed6717a95de4.png)
![image](https://user-images.githubusercontent.com/97726944/164448214-9d093354-7262-415a-b73c-c8ac10949bed.png)

Live: https://www.suprus.com/pages/about-us
SS: 
![image](https://user-images.githubusercontent.com/97726944/164447988-72b2a745-4121-45d6-96fe-2de9274e1133.png)
![image](https://user-images.githubusercontent.com/97726944/164448262-8e801ca6-f246-4582-ab1e-a1f23d1b1533.png)

**Comment by devabulabbas** [comment]
Resolved @Shoaibans

**Comment by Shoaibans** [comment]
The image is fixed but the banner is sometime coming & sometime showing a blank space.

![image](https://user-images.githubusercontent.com/97726944/164706573-5a399c46-efac-48f3-86e1-f70e21c48c5d.png)

**Comment by devRitikTamrakar** [comment]
solved
